version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: hg_db
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: hiddengems
    ports:
      - "3307:3306" # host:container
    volumes:
      - db_data:/var/lib/mysql
    command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: hg_php
    restart: unless-stopped
    environment:
      APP_ENV: local
      APP_DEBUG: "1"
      APP_URL: https://localhost
      DB_DRIVER: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: hiddengems
      DB_USERNAME: root
      DB_PASSWORD: ""
      JWT_SECRET: dev_secret_change_me
      CORS_ALLOWED_ORIGIN: http://localhost
      ENABLE_BANK_SIMULATION: "1"
      REDIS_HOST: redis
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:1.25-alpine
    container_name: hg_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./docker/nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - php

  redis:
    image: redis:7-alpine
    container_name: hg_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  db_data:
