name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  php:
    name: PHP Lint & Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pdo_mysql
          coverage: none
      - name: Validate composer
        run: composer validate --no-interaction
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress
      - name: PHP syntax check
        run: |
          find . -type f -name "*.php" -not -path "./vendor/*" -print0 | xargs -0 -n1 -P4 php -l
      - name: Run tests
        run: composer test

  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: php
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build (no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/php/Dockerfile
          platforms: linux/amd64
          push: false

